/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Panel;

/**
 *
 * @author t00178730
 */
public class Followers extends javax.swing.JPanel {

    /**
     * Creates new form Followers
     */
    public Followers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_follow = new javax.swing.JLabel();
        l_title = new javax.swing.JLabel();
        l_nbfollow = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        b_seefollowlist = new javax.swing.JButton();
        l_news = new javax.swing.JLabel();
        l_username = new javax.swing.JLabel();
        l_tnumber1 = new javax.swing.JLabel();
        b_seeprofile = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(700, 700));

        l_follow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_follow.setText("Number of followers :");

        l_title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        l_title.setText("Free Your Mind");

        l_nbfollow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_nbfollow.setText("0");

        b_seefollowlist.setText("See profile");
        b_seefollowlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seefollowlistActionPerformed(evt);
            }
        });

        l_news.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_news.setText("My followers");

        l_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_username.setText("User Name");

        l_tnumber1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_tnumber1.setText("T00000000");

        b_seeprofile.setText("Back Home");
        b_seeprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seeprofileActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_title)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(l_tnumber1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_username)
                            .addComponent(b_seeprofile))
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_seefollowlist)
                        .addGap(120, 120, 120)
                        .addComponent(l_follow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_nbfollow)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_news)
                            .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_title)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_news)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(l_tnumber1)
                            .addGap(18, 18, 18)
                            .addComponent(l_username)
                            .addGap(18, 18, 18)
                            .addComponent(b_seeprofile))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_follow)
                    .addComponent(l_nbfollow)
                    .addComponent(b_seefollowlist))
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_seefollowlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seefollowlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_seefollowlistActionPerformed

    private void b_seeprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seeprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_seeprofileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b_seefollowlist;
    public javax.swing.JButton b_seeprofile;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_follow;
    public javax.swing.JLabel l_nbfollow;
    private javax.swing.JLabel l_news;
    private javax.swing.JLabel l_title;
    public javax.swing.JLabel l_tnumber1;
    public javax.swing.JLabel l_username;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
