/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Panel;

import entities.Member;
import entities_DAO.MemberDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author t00178747
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    String tnumberConnected = "";

    public Profile() {
        initComponents();
        this.setPreferredSize(new Dimension(700, 700));
        this.setBackground(Color.LIGHT_GRAY);
        
        this.t_city.setEditable(false);
        this.t_county.setEditable(false);
        this.t_dateBirth.setEditable(false);
        this.t_email.setEditable(false);
        this.t_name.setEditable(false);
        this.t_name.setEditable(false);
        this.t_nickname.setEditable(false);
        this.t_password.setEditable(false);
        this.t_password1.setEditable(false);
        this.t_street.setEditable(false);
        this.t_surname.setEditable(false);
        this.t_tnumber.enable(false);
        this.b_saveModification.setEnabled(false);
        
// ========== FOR THE IMAGE AND UPLOAD =============
        JLabel l_loadImage = new JLabel("Select an image from your Computer");
        JButton b_loadImage = new JButton("Load");
        l_loadImage.setBounds(360, 575, 250, 15);
        b_loadImage.setBounds(575, 570, 70, 20);
        this.add(l_loadImage);
        this.add(b_loadImage);

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/Ressources/rsz_profile_image.png"));
        } catch (IOException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon = new ImageIcon(img);
        JLabel label = new JLabel(icon);

        label.setBounds(320, 400, 233, 216);
        this.add(label);
    }

    public void getTnumberConnected(String tnumber) {
        tnumberConnected = tnumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_search1 = new javax.swing.JTextField();
        b_search1 = new javax.swing.JButton();
        l_news1 = new javax.swing.JLabel();
        l_username1 = new javax.swing.JLabel();
        l_tnumber2 = new javax.swing.JLabel();
        b_seeprofile1 = new javax.swing.JButton();
        b_seerecommend1 = new javax.swing.JButton();
        b_seelibrary1 = new javax.swing.JButton();
        b_disconnect1 = new javax.swing.JButton();
        l_follow1 = new javax.swing.JLabel();
        l_title1 = new javax.swing.JLabel();
        l_nbfollow1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        b_seefollowlist1 = new javax.swing.JButton();
        l_followers1 = new javax.swing.JLabel();
        l_nbfollowers1 = new javax.swing.JLabel();
        b_seefollowerslist1 = new javax.swing.JButton();
        sp_newsfeed1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        l_news = new javax.swing.JLabel();
        b_editProfile = new javax.swing.JButton();
        b_backHome = new javax.swing.JButton();
        l_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        t_name = new javax.swing.JTextField();
        t_surname = new javax.swing.JTextField();
        t_dateBirth = new javax.swing.JTextField();
        l_tnumber = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        l_password = new javax.swing.JLabel();
        t_street = new javax.swing.JTextField();
        l_password1 = new javax.swing.JLabel();
        t_city = new javax.swing.JTextField();
        l_nickname = new javax.swing.JLabel();
        t_county = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        l_asterix1 = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_asterix2 = new javax.swing.JLabel();
        l_surname = new javax.swing.JLabel();
        l_dateBirth = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        l_street = new javax.swing.JLabel();
        l_city = new javax.swing.JLabel();
        l_county = new javax.swing.JLabel();
        b_saveModification = new javax.swing.JButton();
        t_tnumber = new javax.swing.JTextField();
        t_password = new javax.swing.JTextField();
        t_password1 = new javax.swing.JTextField();
        t_nickname = new javax.swing.JTextField();
        l_asterix3 = new javax.swing.JLabel();
        l_indication = new javax.swing.JLabel();
        l_indication1 = new javax.swing.JLabel();
        l_indication2 = new javax.swing.JLabel();
        l_asterix4 = new javax.swing.JLabel();
        l_asterix5 = new javax.swing.JLabel();
        l_asterix6 = new javax.swing.JLabel();
        l_asterix7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        tf_search1.setText("Enter an artist, a music, an album...");
        tf_search1.setToolTipText("");

        b_search1.setText("Search");

        l_news1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_news1.setText("News Feed");

        l_username1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_username1.setText("User Name");

        l_tnumber2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_tnumber2.setText("T00000000");

        b_seeprofile1.setText("See my profile");

        b_seerecommend1.setText("See my recommendations");

        b_seelibrary1.setText("See my library");

        b_disconnect1.setText("Disconnect");

        l_follow1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_follow1.setText("Your follow list");

        l_title1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        l_title1.setText("Free Your Mind");

        l_nbfollow1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_nbfollow1.setText("0");

        b_seefollowlist1.setText("See My Follow List");

        l_followers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_followers1.setText("Followers");

        l_nbfollowers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_nbfollowers1.setText("0");

        b_seefollowerslist1.setText("See My Followers");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp_newsfeed1.setViewportView(jTable2);

        l_news.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_news.setText("Profile");

        b_editProfile.setText("Edit my profile");
        b_editProfile.setToolTipText("");
        b_editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editProfileActionPerformed(evt);
            }
        });

        b_backHome.setText("Back Home");

        l_title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        l_title.setText("Free Your Mind");

        t_name.setToolTipText("");

        t_surname.setToolTipText("");

        t_dateBirth.setToolTipText("");

        l_tnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_tnumber.setText("T-Number: ");

        t_email.setToolTipText("");

        l_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_password.setText("Password: ");

        t_street.setToolTipText("");

        l_password1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_password1.setText("Password (again):");

        t_city.setToolTipText("");

        l_nickname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_nickname.setText("Nickname:");

        t_county.setToolTipText("");

        l_asterix1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix1.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix1.setText("*");

        l_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_name.setText("Name:");

        l_asterix2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix2.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix2.setText("*");

        l_surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_surname.setText("Surname:");

        l_dateBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_dateBirth.setText("Date of birth:");

        l_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_email.setText("Email:");

        l_street.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_street.setText("Street:");

        l_city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_city.setText("City:");

        l_county.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_county.setText("County:");

        b_saveModification.setText("Save Modification");
        b_saveModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveModificationActionPerformed(evt);
            }
        });

        t_tnumber.setToolTipText("");

        t_password.setToolTipText("");

        t_password1.setToolTipText("");

        t_nickname.setToolTipText("");

        l_asterix3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix3.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix3.setText("*");

        l_indication.setText("(This information will be only visible for you)");

        l_indication1.setText("(This information will be only visible for you)");

        l_indication2.setText("(dd/mm/yyyy)");

        l_asterix4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix4.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix4.setText("*");

        l_asterix5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix5.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix5.setText("*");

        l_asterix6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix6.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix6.setText("*");

        l_asterix7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_asterix7.setForeground(new java.awt.Color(204, 0, 0));
        l_asterix7.setText("*");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Fiels marqued by this asterix must are mandatory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_backHome)
                            .addComponent(b_editProfile))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_tnumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_tnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_asterix1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_password1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_asterix2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_nickname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_asterix3))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_indication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_asterix4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_surname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_indication1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_asterix5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_dateBirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_indication2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_asterix6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_county)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_county, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_asterix7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(b_saveModification))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_street)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_street, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_city)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_city, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_title)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_news)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_title)
                .addGap(104, 104, 104)
                .addComponent(l_news)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_editProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_backHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_tnumber)
                            .addComponent(t_tnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_password)
                            .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_asterix1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_password1)
                            .addComponent(t_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_asterix2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_nickname)
                            .addComponent(t_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_asterix3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_name)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_indication)
                            .addComponent(l_asterix4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_surname)
                            .addComponent(t_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_indication1)
                            .addComponent(l_asterix5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_dateBirth)
                            .addComponent(t_dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_indication2)
                            .addComponent(l_asterix6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_email)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_street)
                            .addComponent(t_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_county)
                            .addComponent(t_county, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_city)
                            .addComponent(t_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_saveModification)
                            .addComponent(l_asterix7)
                            .addComponent(jLabel1))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_saveModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveModificationActionPerformed
        String tnumber = "";
        String password = "";
        String nickname = "";
        String firstname = "";
        String surname = "";
        Date dateBirth = null;
        String email = "";
        String street = "";
        String city = "";
        String county = "";
        String country = "";

        tnumber = this.t_tnumber.getText();
        password = this.t_password.getText();
        nickname = this.t_nickname.getText();
        firstname = this.t_name.getText();
        surname = this.t_surname.getText();
        email = this.t_email.getText();
        street = this.t_street.getText();
        city = this.t_city.getText();
        county = this.t_county.getText();

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MMM/yyyy");
        String dateInString = "";
        dateInString = this.t_dateBirth.getText();
        if (!dateInString.equalsIgnoreCase("")) {
            try {
                dateBirth = formatter.parse(dateInString);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
        MemberDAO memberDAO = new MemberDAO();
        Member member = null;

        if (!tnumber.equalsIgnoreCase("") && !password.equalsIgnoreCase("")
                && !nickname.equalsIgnoreCase("") && !this.t_password1.getText().equalsIgnoreCase("")
                && dateBirth != null) {
            member = new Member();
            member.setTnumber(tnumber);
            member.setPassword(password);
            member.setNickname(nickname);
            member.setFirstname(firstname);
            member.setSurname(surname);
            member.setEmail_addr(email);
            member.setStreet(street);
            member.setCity(city);
            member.setCounty(county);
        } else {
            //  this.l_error.setVisible(true);
        }

        if (member != null && memberDAO.findByTnumber(tnumber) == null) {
            //  memberDAO.create(member);
            // canBeConnected = true;
        }

        // canBeConnected = true;
    }//GEN-LAST:event_b_saveModificationActionPerformed

    private void b_editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editProfileActionPerformed
         this.t_city.setEditable(true);
        this.t_county.setEditable(true);
        this.t_dateBirth.setEditable(true);
        this.t_email.setEditable(true);
        this.t_name.setEditable(true);
        this.t_name.setEditable(true);
        this.t_nickname.setEditable(true);
        this.t_password.setEditable(true);
        this.t_password1.setEditable(true);
        this.t_street.setEditable(true);
        this.t_surname.setEditable(true);
        this.b_saveModification.setEnabled(true);
    }//GEN-LAST:event_b_editProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b_backHome;
    public javax.swing.JButton b_disconnect1;
    public javax.swing.JButton b_editProfile;
    public javax.swing.JButton b_saveModification;
    public javax.swing.JButton b_search1;
    public javax.swing.JButton b_seefollowerslist1;
    public javax.swing.JButton b_seefollowlist1;
    public javax.swing.JButton b_seelibrary1;
    public javax.swing.JButton b_seeprofile1;
    public javax.swing.JButton b_seerecommend1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l_asterix1;
    private javax.swing.JLabel l_asterix2;
    private javax.swing.JLabel l_asterix3;
    private javax.swing.JLabel l_asterix4;
    private javax.swing.JLabel l_asterix5;
    private javax.swing.JLabel l_asterix6;
    private javax.swing.JLabel l_asterix7;
    private javax.swing.JLabel l_city;
    private javax.swing.JLabel l_county;
    private javax.swing.JLabel l_dateBirth;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_follow1;
    private javax.swing.JLabel l_followers1;
    private javax.swing.JLabel l_indication;
    private javax.swing.JLabel l_indication1;
    private javax.swing.JLabel l_indication2;
    private javax.swing.JLabel l_name;
    public javax.swing.JLabel l_nbfollow1;
    public javax.swing.JLabel l_nbfollowers1;
    private javax.swing.JLabel l_news;
    private javax.swing.JLabel l_news1;
    private javax.swing.JLabel l_nickname;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_password1;
    private javax.swing.JLabel l_street;
    private javax.swing.JLabel l_surname;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_title1;
    private javax.swing.JLabel l_tnumber;
    public javax.swing.JLabel l_tnumber2;
    public javax.swing.JLabel l_username1;
    public javax.swing.JScrollPane sp_newsfeed1;
    private javax.swing.JTextField t_city;
    private javax.swing.JTextField t_county;
    private javax.swing.JTextField t_dateBirth;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_nickname;
    private javax.swing.JTextField t_password;
    private javax.swing.JTextField t_password1;
    private javax.swing.JTextField t_street;
    private javax.swing.JTextField t_surname;
    private javax.swing.JTextField t_tnumber;
    public javax.swing.JTextField tf_search1;
    // End of variables declaration//GEN-END:variables
}
