/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Panel;

import entities.Member;
import entities.Playlist;
import entities_DAO.MemberDAO;
import entities_DAO.PlaylistDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author t00178760
 */
public class SeeLibrary extends javax.swing.JPanel {

    /**
     * Creates new form SeeLibrary
     */
    MemberDAO memberDAO = new MemberDAO();
    Member member = new Member();
    PlaylistDAO playlistDAO = new PlaylistDAO();
    List<Playlist> playlists = new ArrayList();
    
    String tnumber ="t10000000";
    
    public SeeLibrary() {
        initComponents();
        
        this.setPreferredSize(new Dimension(700, 700));
        this.setBackground(Color.LIGHT_GRAY);
    }
    
    public void setTnumber(String tnumberToGet){
             tnumber =tnumberToGet;
                System.out.println(tnumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_title = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        user_tnumber = new javax.swing.JLabel();
        libraryLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        l_title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        l_title.setText("Free Your Mind");

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username.setText("User Name");

        user_tnumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user_tnumber.setText("T00000000");

        libraryLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        libraryLabel.setText("Library");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(user_tnumber))
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_title)
                    .addComponent(libraryLabel))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_tnumber)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(libraryLabel))
                .addGap(30, 30, 30)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel libraryLabel;
    public javax.swing.JLabel user_tnumber;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
