/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author t00178747
 */
public class LogIn extends javax.swing.JPanel {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_title = new javax.swing.JLabel();
        l_subscribe = new javax.swing.JLabel();
        l_tnumber = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        l_password1 = new javax.swing.JLabel();
        l_nickname = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        l_name = new javax.swing.JLabel();
        l_surname = new javax.swing.JLabel();
        l_dateBirth = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        l_street = new javax.swing.JLabel();
        l_city = new javax.swing.JLabel();
        l_county = new javax.swing.JLabel();
        l_country = new javax.swing.JLabel();
        b_subscribe = new javax.swing.JButton();
        b_backHome = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 700));

        l_title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        l_title.setText("Free Your Mind");

        l_subscribe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_subscribe.setText("Subscribe");

        l_tnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_tnumber.setText("T-Number: ");

        l_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_password.setText("Password: ");

        l_password1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_password1.setText("Password (again):");

        l_nickname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_nickname.setText("Nickname:");

        l_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_name.setText("Name:");

        l_surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_surname.setText("Surname:");

        l_dateBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_dateBirth.setText("Date of birth:");

        l_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_email.setText("Email:");

        l_street.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_street.setText("Street:");

        l_city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_city.setText("City:");

        l_county.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_county.setText("County:");

        l_country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_country.setText("Country:");

        b_subscribe.setText("Subscribe");
        b_subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_subscribeActionPerformed(evt);
            }
        });

        b_backHome.setText("Back home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(l_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_tnumber)
                            .addComponent(l_subscribe)
                            .addComponent(l_password)
                            .addComponent(l_password1)
                            .addComponent(l_nickname)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_name)
                            .addComponent(l_surname)
                            .addComponent(l_dateBirth)
                            .addComponent(l_email)
                            .addComponent(l_street)
                            .addComponent(l_city)
                            .addComponent(l_county)
                            .addComponent(l_country))))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_subscribe)
                .addGap(18, 18, 18)
                .addComponent(b_backHome)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(l_title)
                .addGap(29, 29, 29)
                .addComponent(l_subscribe)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(l_tnumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_nickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_surname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_dateBirth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_street)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_city)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_county)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_country)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_subscribe)
                    .addComponent(b_backHome))
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_subscribeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_subscribeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_backHome;
    private javax.swing.JButton b_subscribe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_city;
    private javax.swing.JLabel l_country;
    private javax.swing.JLabel l_county;
    private javax.swing.JLabel l_dateBirth;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_nickname;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_password1;
    private javax.swing.JLabel l_street;
    private javax.swing.JLabel l_subscribe;
    private javax.swing.JLabel l_surname;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_tnumber;
    // End of variables declaration//GEN-END:variables
}
