/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Label;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author t00178747
 */
public class Try extends javax.swing.JPanel {

    /**
     * Creates new form Try
     */
    public Try() {
        initComponents();
        
       /* this.setPreferredSize(new Dimension(700, 700));
        Label label = new Label("Coucou");
        label.setBounds(100, 100, 100, 100);

        Object[][] donnees = {
            {"Johnathan", "Sykes", Color.red, true, Sport.TENNIS},
            {"Nicolas", "Van de Kampf", Color.black, true, Sport.FOOTBALL},
            {"Damien", "Cuthbert", Color.cyan, true, Sport.RIEN},
            {"Corinne", "Valance", Color.blue, false, Sport.NATATION},
            {"Emilie", "Schrödinger", Color.magenta, false, Sport.FOOTBALL},
            {"Delphine", "Duke", Color.yellow, false, Sport.TENNIS},
            {"Eric", "Trump", Color.pink, true, Sport.FOOTBALL},};
        

        String[] entetes = {"Prénom", "Nom", "Couleur favorite", "Homme", "Sport"};

        JTable tableau = new JTable(donnees, entetes);
        System.out.println(tableau.getWidth());
        tableau.setBounds(0, 0, 500,  150);
        this.add(new JScrollPane(tableau), BorderLayout.CENTER);
        this.add(tableau);
        this.add(label);

        this.setVisible(true);*/
    }

    public enum Sport {

        TENNIS,
        FOOTBALL,
        NATATION,
        RIEN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_textArea = new javax.swing.JTextArea();

        t_textArea.setColumns(20);
        t_textArea.setRows(5);
        jScrollPane1.setViewportView(t_textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t_textArea;
    // End of variables declaration//GEN-END:variables
}
